# Generated by Django 5.2.17 on 2026-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numero_patrimonio", models.IntegerField()),
                ("tipo", models.CharField(max_length=50)),
                ("em_uso", models.BooleanField(default=False)),
            ],
        ),
    ]
